# Generated by Django 5.2.6 on 2025-09-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_json', models.JSONField()),
                ('is_fraud', models.BooleanField()),
                ('risk', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('model_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
